# Generated by Django 3.0.8 on 2020-09-30 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03084a4e-ef22-429d-8278-b58d65c85987'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedulelist',
            name='response',
            field=models.CharField(default='OK', max_length=10),
        ),
    ]
