# Generated by Django 3.0.8 on 2020-09-30 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200930_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e08c8496-ca86-49f1-a560-fa46454cdaad'), editable=False, primary_key=True, serialize=False),
        ),
    ]
