# Generated by Django 3.0.8 on 2020-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedata_keyword', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logkeywordcount',
            old_name='json_data',
            new_name='json_data_media',
        ),
        migrations.AddField(
            model_name='logkeywordcount',
            name='json_data_name',
            field=models.CharField(default={}, max_length=200),
            preserve_default=False,
        ),
    ]
